name: rick_and_morty
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  dio: ^5.9.1
  go_router: ^17.1.0
  get_it: ^9.2.1
  stream_transform: ^2.1.1
  bloc_concurrency: ^0.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/